export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_CHOOSER = 'SET_COUNTER';
export const ENGLISH_CHOOSER = 'ENGLISH_CHOOSER';
export const NOVOSLOVNICA_CHOOSER = 'NOVOSLOVNICA_CHOOSER';
export const INTERSLAVIC_CHOOSER = 'INTERSLAVIC_CHOOSER';
export const LOGGED_IN = 'LOGGED_IN';
export const LOGGED_OUT = 'LOGGED_OUT';
